name: Pre-Commit Format Check

on:
  push:
    paths:
      - "**.py"
      - "pyproject.toml"
  pull_request:
    paths:
      - "**.py"
      - "pyproject.toml"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install uv
          uv sync --dev

      - name: Run pre-commit check
        run: uv run pre-commit run --all-files
